###########################
#                         #
# OpenFlipper GitLAB CI   #
#                         #
###########################

stages:
  - Build
  - Test
  - Deploy

variables:
  GET_SOURCES_ATTEMPTS: 3
  CTEST_OUTPUT_ON_FAILURE: 1

{linux.yml}

{windows.yml}

{mac.yml}

{other.yml}
