#-----------  Job Informations:
# Type:       Test: {{BUILDTYPE}}
# OS:         Linux
# Compiler:   {{COMPILER}}
# Language:   {{LANGUAGE}}
# QT Version: {{QTVERSION}}

test-{{BUILDTYPE}}-{{COMPILER}}-{{LANGUAGE}}-{{QTVERSION}}:
  stage: Test
  image: graphics.rwth-aachen.de:4567/docker/docker/docker-openflipper-container
  variables:     
    COMPILER:       "{{COMPILER}}"     
    LANGUAGE:       "{{LANGUAGE}}"     
    QTVERSION:      "{{QTVERSION}}"     
    BUILDTYPE:      "{{BUILDTYPE}}"
    GIT_STRATEGY: none
  script: "artifacts/CI/ci-linux-test.sh"
  tags:
    - Docker
  dependencies:
    - build-{{BUILDTYPE}}-{{COMPILER}}-{{LANGUAGE}}-{{QTVERSION}}
  needs: [build-{{BUILDTYPE}}-{{COMPILER}}-{{LANGUAGE}}-{{QTVERSION}}]
  artifacts:
    paths:
       - build-{{BUILDTYPE}}-{{COMPILER}}-{{LANGUAGE}}-{{QTVERSION}}/Testing/Temporary/LastTest.log   

#
#-----------
