##############################
#
#    LINUX JOBS
#
##############################

{linux-template-job-release.yml, COMPILER=gcc,   LANGUAGE=cpp11, QT_VERSION=qt5.11.2}

{linux-template-job-release.yml, COMPILER=gcc,   LANGUAGE=cpp11, QT_VERSION=qt5.12.2}

{linux-template-job-release.yml,    COMPILER=gcc,   LANGUAGE=cpp11, QT_VERSION=qt5.13.0}

{linux-template-job-full.yml,    COMPILER=gcc,   LANGUAGE=cpp11, QT_VERSION=qt5.15.1}
{linux-template-job-full.yml,    COMPILER=clang, LANGUAGE=cpp11, QT_VERSION=qt5.15.1}

cppcheck:
  # image: graphics.rwth-aachen.de:4567/docker/docker/docker-openflipper-container
  stage: Build
  script: "CI/ci-cppcheck.sh"
  variables:
     GIT_SUBMODULE_STRATEGY: recursive
  tags:
    - Linux
    - stretch
    - MultiThreads

  artifacts:
    paths:
      - cppcheck.log
      
