#-----------  Job Informations:
# Type:       Build: {{BUILDTYPE}}
# OS:         Linux
# Compiler:   {{COMPILER}}
# Language:   {{LANGUAGE}}
# QT Version: {{QT_VERSION}}
# Include what you use test

iwyu-{{BUILDTYPE}}-{{COMPILER}}-{{LANGUAGE}}-{{QT_VERSION}}:
  stage: Build
  # image: graphics.rwth-aachen.de:4567/docker/docker/docker-openflipper-container:{{ISO_TAG}}
  variables:
    COMPILER: "{{COMPILER}}"
    LANGUAGE: "{{LANGUAGE}}"
    QTVERSION: "{{QT_VERSION}}"
    BUILDTYPE: "{{BUILDTYPE}}"
    GIT_SUBMODULE_STRATEGY: recursive
    IWYU: "yes"
  script: "CI/ci-linux-build.sh"
  tags:
    - Linux
    - stretch
  artifacts:
    expire_in: 1 week
    paths:
      - build-{{BUILDTYPE}}-{{COMPILER}}-{{LANGUAGE}}-{{QT_VERSION}}-iwyu/compile_commands.json
      - build-{{BUILDTYPE}}-{{COMPILER}}-{{LANGUAGE}}-{{QT_VERSION}}-iwyu/iwyu.dump

#
#-----------
