##############################
#
#    LINUX JOBS
#
##############################

{linux-template-job.yml, COMPILER=gcc,   LANGUAGE=cpp11, QT_VERSION=qt5.11.2, ISO_TAG=debian}
{linux-template-job.yml, COMPILER=clang, LANGUAGE=cpp11, QT_VERSION=qt5.11.2, ISO_TAG=debian}

{linux-template-job.yml, COMPILER=gcc,   LANGUAGE=cpp11, QT_VERSION=qt5.12.2, ISO_TAG=debian}
{linux-template-job.yml, COMPILER=clang, LANGUAGE=cpp11, QT_VERSION=qt5.12.2, ISO_TAG=debian}

{linux-template-job.yml, COMPILER=gcc,   LANGUAGE=cpp11, QT_VERSION=qt5.13.0, ISO_TAG=debian}
{linux-template-job.yml, COMPILER=clang, LANGUAGE=cpp11, QT_VERSION=qt5.13.0, ISO_TAG=debian}

{linux-template-job.yml, COMPILER=gcc,   LANGUAGE=cpp11, QT_VERSION=qt5.13.2, ISO_TAG=debian}
{linux-template-job.yml, COMPILER=clang, LANGUAGE=cpp11, QT_VERSION=qt5.13.2, ISO_TAG=debian}

##############################

# Temporarly disabled ubuntu builds
#{linux-template-job.yml, COMPILER=gcc,   LANGUAGE=cpp11, QT_VERSION=qt5.11.2, ISO_TAG=ubuntu}
#{linux-template-job.yml, COMPILER=clang, LANGUAGE=cpp11, QT_VERSION=qt5.11.2, ISO_TAG=ubuntu}
#
#{linux-template-job.yml, COMPILER=gcc,   LANGUAGE=cpp11, QT_VERSION=qt5.12.2, ISO_TAG=ubuntu}
#{linux-template-job.yml, COMPILER=clang, LANGUAGE=cpp11, QT_VERSION=qt5.12.2, ISO_TAG=ubuntu}
#
#{linux-template-job.yml, COMPILER=gcc,   LANGUAGE=cpp11, QT_VERSION=qt5.13.0, ISO_TAG=ubuntu}
#{linux-template-job.yml, COMPILER=clang, LANGUAGE=cpp11, QT_VERSION=qt5.13.0, ISO_TAG=ubuntu}
#
#{linux-template-job.yml, COMPILER=gcc,   LANGUAGE=cpp11, QT_VERSION=qt5.13.2, ISO_TAG=ubuntu}
#{linux-template-job.yml, COMPILER=clang, LANGUAGE=cpp11, QT_VERSION=qt5.13.2, ISO_TAG=ubuntu}


cppcheck:
  # image: graphics.rwth-aachen.de:4567/docker/docker/docker-openflipper-container
  stage: Build
  script: "CI/ci-cppcheck.sh"
  variables:
     GIT_SUBMODULE_STRATEGY: recursive
  tags:
    - Linux
    - stretch
    - MultiThreads

  artifacts:
    paths:
      - cppcheck.log
      