##############################
#
#    MAC JOBS
#
##############################

{mac-template-job.yml, LANGUAGE=cpp11, QT_TAG=qt5113}

{mac-template-job.yml, LANGUAGE=cpp17, QT_TAG=qt5113}

{mac-M1-template-job.yml}
