##############################
#
#    GENERAL JOBS
#
##############################

Doc-publish:
   stage: Deploy 
   only:
      - master
      - unstable
   script: "CI/ci-doc.sh"
   tags:
      - Linux
      - stretch
   dependencies: []
   variables:
      GIT_SUBMODULE_STRATEGY: recursive
   artifacts:
     paths:
        - build-release/Doxygen-warning.log 
        - build-release/Doxygen-error.log

Sources:
   stage: Deploy
   only:
      - master
   script: "CI/ci-source.sh"
   tags:
      - Linux
      - stretch
   dependencies: []
   variables:
      GIT_SUBMODULE_STRATEGY: recursive
   artifacts:
      paths:
        - OpenFlipper*.zip
        - OpenFlipper*.tar.bz2
        - OpenFlipper*.tar.gz
 