##############################
#
#    WINDOWS JOBS
#
##############################

{windows-template-job.yml, COMPILER=VS2015, QT_VERSION=Qt5.14.1, QT_TAG=Qt5141, ARCH=x64}

{windows-template-job.yml, COMPILER=VS2017, QT_VERSION=Qt5.14.1, QT_TAG=Qt5141, ARCH=x64}
