#-----------  Job Informations:
# Type:       Deploy
# OS:         Windows
# Arch:       {{ARCH}}
# QT Version: {{QT_VERSION}}
# QT Tag:     {{QT_TAG}}
# Compiler:   {{COMPILER}}

Deploy:{{COMPILER}}-{{QT_VERSION}}-{{ARCH}}:
    stage: Deploy
    only:
      - master
      - unstable
    script: "artifacts\\CI\\ci-windows-bootstrap.bat"
    variables:
      GIT_STRATEGY: none
      ARCHITECTURE: "{{ARCH}}"
      QT_VERSION: "{{QT_VERSION}}"
      COMPILER: "{{COMPILER}}"
      STAGE2SCRIPT: ci-windows-deploy.bat
    tags:
      - {{COMPILER}}
      - {{QT_TAG}}
    dependencies:
      - {{COMPILER}}-{{QT_VERSION}}-{{ARCH}}
    needs: [{{COMPILER}}-{{QT_VERSION}}-{{ARCH}}]
    artifacts:
      paths:
        - rel/*.exe

Deploy:{{COMPILER}}-{{QT_VERSION}}-{{ARCH}}-NOPYTHON:
    stage: Deploy
    only:
      - master
      - unstable
    script: "artifacts\\CI\\ci-windows-bootstrap.bat"
    variables:
      GIT_STRATEGY: none
      ARCHITECTURE: "{{ARCH}}"
      QT_VERSION: "{{QT_VERSION}}"
      COMPILER: "{{COMPILER}}"
      STAGE2SCRIPT: ci-windows-deploy.bat
      PYTHON: "no"
    tags:
      - {{COMPILER}}
      - {{QT_TAG}}
    dependencies:
      - {{COMPILER}}-{{QT_VERSION}}-{{ARCH}}-NOPYTHON
    needs: [{{COMPILER}}-{{QT_VERSION}}-{{ARCH}}-NOPYTHON]
    artifacts:
      paths:
        - rel/*.exe

#
#-----------
